---
- hosts: all
  gather_facts: no

  vars:
    privkey: "../.vagrant/machines/student01/virtualbox/private_key"
    pubkey: "../.vagrant/machines/student01/virtualbox/private_key.pub"

  tasks:

    - name: Create SSH pubkey locally in Vagrant directory
      local_action: "shell ssh-keygen -y -f {{ privkey }} > {{ pubkey }}"

    - name: Set authorized SSH key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '{{ pubkey }}') }}"
      become: yes
      with_items:
        - "admin"
        - "auditadm"
        - "dbadm"
        - "guest"
        - "logadm"
        - "secadm"
        - "sysadm"
        - "webadm"
