---
- hosts: all
  gather_facts: no

  tasks:

    - name: Create SSH pubkey locally in Vagrant directory
      local_action: shell ssh-keygen -y -f ../.vagrant/machines/default/virtualbox/private_key > ../.vagrant/machines/default/virtualbox/private_key.pub

    - name: Set authorized SSH key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '../.vagrant/machines/default/virtualbox/private_key.pub') }}"
      become: yes
      with_items:
        - "admin"
        - "auditadm"
        - "dbadm"
        - "guest"
        - "logadm"
        - "secadm"
        - "sysadm"
        - "webadm"
