---
- hosts: all
  gather_facts: no

  pre_tasks:

    - name: Define path to SSH key paths
      set_fact:
        privkey: "../.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

  tasks:

    - name: Fix permissions of SSH key
      local_action: file path="{{ privkey }}" mode="0600"
